[package]
name = "standardnotes-rs"
version = "0.1.0"
authors = ["Lane Sawyer <github@lanesawyer.dev>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "7"
rocket = "0.4.5"
rocket_contrib = "0.4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
